[build]
  # Standardní nastavení pro React
  publish = "build"
  # Tady říkáme: Ignoruj varování (CI=false) a spusť build
  command = "CI=false npm run build"

[build.environment]
  # Verze Node.js
  NODE_VERSION = "22"
  # Pojistka pro NPM
  NPM_FLAGS = "--no-audit"